// REFERENCE IMPLEMENTATION (proven on a real production delivery).
// Copy to scripts/qa-verify.mjs in the new project and adapt the `commands`
// list to the npm scripts that exist. Runs the whole validation battery and
// writes a markdown evidence report to docs/qa/automated-verification-latest.md.
// Wire as: "qa:verify": "node scripts/qa-verify.mjs".
import { spawn } from "node:child_process";
import { writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const commands = [
  {
    name: "traceability",
    command: "node",
    args: ["scripts/check-traceability.mjs"],
  },
  {
    name: "trajectory",
    command: "node",
    args: ["scripts/check-trajectory.mjs"],
  },
  {
    // Real recordings gate: video artifacts exist + asserted + vision met
    // (graceful before Phase 6 — warns, never fails, when no manifest yet).
    name: "recordings",
    command: "node",
    args: ["scripts/check-recordings.mjs"],
  },
  {
    name: "unit-tests",
    command: "npm",
    args: ["run", "test:run"],
  },
  {
    name: "db-integration-tests",
    command: "npm",
    args: ["run", "test:integration"],
  },
  {
    name: "browser-e2e-tests",
    command: "npm",
    args: ["run", "test:e2e"],
  },
  {
    // Guards the committed eval score (quality bar). Needs evals/results/
    // latest.json from the eval-suite workflow — include once evals exist.
    name: "eval-ratchet",
    command: "node",
    args: ["scripts/check-eval-ratchet.mjs"],
  },
  {
    name: "lint",
    command: "npm",
    args: ["run", "lint"],
  },
  {
    name: "production-build",
    command: "npm",
    args: ["run", "build"],
  },
  {
    name: "openspec-all",
    command: "npx",
    args: ["openspec", "validate", "--all", "--strict"],
  },
  {
    name: "openspec-active-list",
    command: "npx",
    args: ["openspec", "list"],
  },
];

const startedAt = new Date();
const results = [];

for (const entry of commands) {
  console.log(`\n==> ${entry.name}`);
  const result = await run(entry.command, entry.args);
  results.push({
    name: entry.name,
    command: [entry.command, ...entry.args].join(" "),
    exitCode: result.exitCode,
    output: result.output.trim(),
  });
  if (result.exitCode !== 0) {
    console.error(`Command failed: ${entry.name}`);
    break;
  }
}

const finishedAt = new Date();
const markdown = renderReport({ startedAt, finishedAt, results });
const outputPath = join(root, "docs", "qa", "automated-verification-latest.md");
await writeFile(outputPath, markdown, "utf8");

const failed = results.find((result) => result.exitCode !== 0);
console.log(`\nWrote ${outputPath}`);
process.exitCode = failed ? failed.exitCode : 0;

function run(command, args) {
  return new Promise((resolve) => {
    const child = spawn(command, args, {
      cwd: root,
      shell: process.platform === "win32",
      env: process.env,
    });
    let output = "";
    child.stdout.on("data", (chunk) => {
      const text = chunk.toString();
      output += text;
      process.stdout.write(text);
    });
    child.stderr.on("data", (chunk) => {
      const text = chunk.toString();
      output += text;
      process.stderr.write(text);
    });
    child.on("close", (exitCode) => {
      resolve({ exitCode: exitCode ?? 1, output });
    });
  });
}

function renderReport({ startedAt, finishedAt, results }) {
  const allPassed = results.every((result) => result.exitCode === 0);
  const rows = results
    .map(
      (result) =>
        `| ${result.name} | \`${result.command}\` | ${result.exitCode === 0 ? "Pass" : "Fail"} | ${result.exitCode} |`,
    )
    .join("\n");
  const details = results
    .map(
      (result) => `## ${result.name}

Command: \`${result.command}\`

Exit code: ${result.exitCode}

\`\`\`text
${result.output || "(no output)"}
\`\`\`
`,
    )
    .join("\n");

  return `# Automated Verification Latest

Generated by \`node scripts/qa-verify.mjs\`.

- Started: ${startedAt.toISOString()}
- Finished: ${finishedAt.toISOString()}
- Overall result: ${allPassed ? "Pass" : "Fail"}

| Check | Command | Result | Exit code |
|---|---|---|---|
${rows}

${details}`;
}
